[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wannier-utils"
version = "0.1.0"
description = "Plotting utilities and styles"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "matplotlib",
    "numpy",
    "pymatgen",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
plot_utils = ["*.mplstyle"]
